-- Regenerates tests/data/*.lua from a CatsEyeXI server checkout. From the repo root:
--   luajit tools/gen_resources.lua <path-to-catseyexi> [commit]
-- Reads sql/spell_list.sql, sql/abilities.sql and sql/status_effects.sql and writes the
-- three lookup tables the data-table tests check job files against. The optional commit
-- is recorded in each file's header so a reader knows which server revision it mirrors.
local root = arg[1];
if root == nil then
    io.stderr:write('usage: luajit tools/gen_resources.lua <path-to-catseyexi> [commit]\n');
    os.exit(2);
end
root = root:gsub('[/\\]+$', '');
local commit = arg[2] or 'unknown';

-- Splits one "INSERT INTO `t` VALUES (...)" line into its values: quoted strings unquoted,
-- numbers as numbers, everything else (NULL, hex blobs, @ELEMENT_* names) as raw text.
-- Some rows carry a trailing "-- note" after the ");", so the match stops at the first ");".
local function parse_values(line)
    local body = line:match('VALUES %((.-)%);');
    if body == nil then return nil; end
    local out, i = {}, 1;
    while i <= #body do
        local c = body:sub(i, i);
        if c == "'" then
            local j = i + 1;
            local s = {};
            while body:sub(j, j) ~= "'" do
                if body:sub(j, j) == '\\' then j = j + 1; end
                table.insert(s, body:sub(j, j));
                j = j + 1;
            end
            table.insert(out, table.concat(s));
            i = j + 1;
        else
            local j = body:find(',', i, true) or (#body + 1);
            local raw = body:sub(i, j - 1);
            table.insert(out, tonumber(raw) or raw);
            i = j;
        end
        if body:sub(i, i) == ',' then i = i + 1; end
    end
    return out;
end

local function rows(file)
    local out = {};
    for line in io.lines(root .. '/sql/' .. file) do
        if line:match('^INSERT INTO') then
            table.insert(out, parse_values(line));
        end
    end
    return out;
end

local function write(file, header, entries)
    local f = assert(io.open('tests/data/' .. file, 'w'));
    f:write(('-- Generated by tools/gen_resources.lua from CatsEyeXI %s; do not edit by hand.\n'):format(commit));
    f:write('-- ' .. header .. '\n');
    f:write('return {\n');
    table.sort(entries, function(a, b) return a[1] < b[1]; end);
    for _, e in ipairs(entries) do f:write(e[2] .. '\n'); end
    f:write('}\n');
    f:close();
end

-- spell_list: spellid, name, jobs, group, family, element, zonemisc, validTargets, skill, mpCost, ...
-- Ninjutsu costs no MP; the server reuses its mpCost column for the tool item id.
local spells = {};
for _, v in ipairs(rows('spell_list.sql')) do
    local mp = v[9] == '@SKILL_NINJUTSU' and 0 or v[10];
    table.insert(spells, { v[1], ('    [%d] = { name = %q, mp = %d },'):format(v[1], v[2], mp) });
end
write('spells.lua', 'spell_list.sql: [spellid] = { name, mp = mpCost }', spells);

-- abilities: abilityId, name, job, level, validTarget, recastTime, recastId, ...
local abilities = {};
for _, v in ipairs(rows('abilities.sql')) do
    table.insert(abilities, { v[1], ('    [%d] = { name = %q, recast = %d },'):format(v[1], v[2], v[7]) });
end
write('abilities.lua', 'abilities.sql: [abilityId] = { name, recast = recastId }', abilities);

-- status_effects: id, name, ...
local effects = {};
for _, v in ipairs(rows('status_effects.sql')) do
    table.insert(effects, { v[1], ('    [%d] = %q,'):format(v[1], v[2]) });
end
write('status_effects.lua', 'status_effects.sql: [id] = name', effects);
